version: "3.8"


volumes:
  db_data:
    name: "fastapi_quickstart-PostgreSQL-DATA"
  pgadmin_data:
    name: "fastapi_quickstart-PGAdmin-DATA"
  redis_data:
    name: "fastapi_quickstart-Redis-DATA"
  backend_data:
    name: "fastapi_quickstart-DATA"


services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "0.0.0.0:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres -h db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: elestio/pgadmin
    restart: unless-stopped
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    env_file:
      - .env
    environment:
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - db

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"  # Redis Server
      - "0.0.0.0:8001:8001"  # RedisInsight
    volumes:
      - "redis_data:/data"
      - "./redis/data:/data"
      - "./redis/redis.conf:/redis-stack.conf"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "backend_data:/backend"
      - "./:/backend"
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8000/api/v1/ || exit 1"]
      start_period: 10s
      interval: 30s
      timeout: 2s
      retries: 3
