version: 3

includes:
  test:
    taskfile: ./tests/Taskfile.yaml
  mig:
    taskfile: ./migrations/Taskfile.yaml

vars:
  RUNNER: "poetry run"

dotenv:
  - ".env"

tasks:
  lint:
    desc: "Run linters, not change code."
    vars:
      ABSOLUTE: "A"
      MODULES: "A"
      AVERAGE: "A"
      EXCLUDE: "tests*"
    cmds:
      - '{{.RUNNER}} xenon . -b {{.ABSOLUTE}} -m {{.MODULES}} -a {{.AVERAGE}} -e "{{.EXCLUDE}}"'
      - "{{.RUNNER}} ruff check ."
    ignore_error: true


  lint:docs:
    desc: "Run coverage for documentation."
    summary: "Default usage: `task lint:docs`.

    Extended usage: `task lint:docs -- v` (Increasing verbosity level to `-vv`, `-v` by default).
    "
    cmd: "{{.RUNNER}} interrogate {{.VERBOSITY}}{{.CLI_ARGS}}"
    vars:
      VERBOSITY: "-v"

  lint:types:
    desc: "Run mypy (type annotations linter)."
    cmd: "{{.RUNNER}} mypy ."

  lint:plus:
    desc: "Run all linters and ignore errors."
    cmds:
      - task: lint
      - task: lint:docs
      - task: lint:types
    ignore_error: true

  format:
    desc: "Run formatters and auto fixing errors."
    cmds:
      - "{{.RUNNER}} ruff format"
      - "{{.RUNNER}} ruff check . --fix"

  pre:
    desc: "Run `format` then `lint`."
    cmds:
      - task: format
      - task: lint
      - task: test:cov

  run:gu:
    desc: "Start web server via `Gunicorn` (production mode)."
    cmd: "{{.RUNNER}} gunicorn apps.__main__:app -c gunicorn.conf.py"

  run:py:
    desc: "Start web server via `Uvicorn` (development mode)."
    cmd: "{{.RUNNER}} python -m apps"

  run:
    desc: "Run migrations and then start web."
    cmds:
      - task: mig:head
      - task: run:gu

  req:
    desc: "Generate main `requirements.txt` file from Poetry."
    vars:
      FORMAT: "requirements.txt"
    cmd: "poetry export --without-hashes --only main -f {{.FORMAT}} -o requirements.txt"
