version: 3

tasks:
  default:
    aliases: ["head"]
    desc: "Run migrations to `head`."
    cmd: "{{.RUNNER}} alembic upgrade head"

  new:
    desc: "Autogenerate migration"
    requires:
      vars:
        - id
        - msg
    cmd: "{{.RUNNER}} alembic revision --autogenerate --rev-id {{.id}} -m {{.msg}}"

  sql:
    desc: "Generate .sql migration for specified revision"
    summary: |
      Generates .sql migration for specified revision by `id`.
      You can also merge multiple migrations in one file, just provide `end_id` variable.
      Example: task mig:sql id=0001 end_id=0002
    requires:
      vars:
        - id
    cmd: >
      {{.RUNNER}} alembic upgrade
      {{if and .end_id .id }}
      {{.id}}:{{.end_id}}
      {{else}}
      {{.id}}
      {{end}}
      --sql

  base:
    desc: "Downgrade migration to `base`."
    prompt: "Are you sure that you need to roll back all migrations? All existing data will be removed from DB!"
    aliases: ["zero"]
    cmd: "{{.RUNNER}} alembic downgrade base"

  current:
    desc: "Returns information about `current` migration applied."
    cmd: "{{.RUNNER}} alembic current"

  up:
    desc: "Upgrade `+1` migration from `current`."
    cmd: "{{.RUNNER}} alembic upgrade +1"
    ignore_error: true

  down:
    desc: "Downgrade `-1` migration from `current`."
    cmd: "{{.RUNNER}} alembic downgrade -1"

  check:
    desc: "Check for new upgrade operations."
    cmd: "{{.RUNNER}} alembic check"

  show:
    desc: "Get details about migration by revision `id`."
    requires:
      vars:
        - id
    ignore_error: true
    cmd: "{{.RUNNER}} alembic show {{.id}}"

  move:
    desc: "Move migration to revision `id` (but doesn't apply it)."
    requires:
      vars:
        - id
    ignore_error: true
    cmd: "{{.RUNNER}} alembic stamp {{.id}}"

  history:
    desc: "Draw all migration's history output."
    summary: "Returns migration's history output, latest at the start and then older."
    cmd: "{{.RUNNER}} alembic history"
