"""todos

Revision ID: 0002
Revises: 0001
Create Date: 2022-09-27 21:30:44.845970+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "to_do",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=128), nullable=False),
        sa.Column("description", sa.VARCHAR(length=256), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_to_do")),
    )
    op.create_index(op.f("ix_to_do_title"), "to_do", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_to_do_title"), table_name="to_do")
    op.drop_table("to_do")
    # ### end Alembic commands ###
